FROM node:14-alpine

ENV proj=project
ARG proj=project
run echo "envirment = ${proj:-project}" && echo "argument = ${proj:-project}"

RUN npx create-react-app $proj --template typescript
workdir $proj

RUN npm install eslint-config-airbnb
RUN npm install eslint-config-airbnb-typescript
RUN npm install eslint-config-prettier
RUN npm install eslint-plugin-import
RUN npm install eslint-plugin-jest
RUN npm install eslint-plugin-jsx-a11y
RUN npm install eslint-plugin-prettier
RUN npm install eslint-plugin-react
RUN npm install eslint-plugin-react-hooks
RUN npm install prettier
RUN npm install react-router-dom
RUN npm install styled-components
RUN npm install @types/react-router-dom
RUN npm install @types/styled-components
RUN npm install @types/react-dom
RUN npm install @typescript-eslint/eslint-plugin
RUN npm install @typescript-eslint/parser
RUN npm install react-i18next i18next --save
RUN npm install react-i18next @types/react-i18next i18next @types/i18next
RUN npm install node-sass
RUN npm install scss
RUN npm install axios
RUN npm install http-proxy-middleware
RUN npm install react-helmet-async



COPY Dockerfile.dev /$proj/Dockerfile.dev
# COPY eslintrc.js /$proj/.eslintrc.js
# COPY prettierrc.js /$proj/.prettierrc.js

cmd cp -R . /app/$proj



