FROM node:14-alpine

ENV proj=project
ARG proj=project
run echo "envirment = ${proj:-project}" && echo "argument = ${proj:-project}"

RUN npx create-react-app $proj
workdir $proj

RUN npm install eslint-config-airbnb
RUN npm install eslint-config-prettier
RUN npm install eslint-plugin-import
RUN npm install eslint-plugin-jest
RUN npm install eslint-plugin-jsx-a11y
RUN npm install eslint-plugin-prettier
RUN npm install eslint-plugin-react
RUN npm install eslint-plugin-react-hooks
RUN npm install prettier
RUN npm install react-router-dom
RUN npm install styled-components
RUN npm install @types/react-router-dom
RUN npm install @types/styled-components
RUN npm install @types/react-dom
RUN npm install react-i18next i18next --save
RUN npm install react-i18next @types/react-i18next i18next @types/i18next
RUN npm install axios
RUN npm install http-proxy-middleware


COPY Dockerfile.dev /$proj/Dockerfile.dev

cmd cp -R . /app/$proj


#run rm -rf node_modules
#run echo curl -s "https://www.toptal.com/developers/gitignore/api/macos" > gitignore
#RUN touch .eslintrc.js
#RUN echo "hello" > .eslintrc.js


