export const Color = {
  select: {
    selectWhiteColor: "#fff",
    selectDarkCyanColor: "darkcyan",
  },

  header: {
    headerWrapBgColor: "#fff",
    headerWrapBoxShaow: "rgb(0 0 0 / 7%) 0px 3px 4px 0px",
    headerControllerBgColor: "#eee",
    headerPlaceholderFontColor: "#999",
  },

  home: {
    homeColor: "#999",
    homeBorder: "1px solid #ccc",
  },

  product: {
    productColor: "#999",
    productColor2: "#ababab",
    productBorder1: "1px solid #ccc",
    productBorder2: "1px solid #ececec",
    productBorder3: "1px solid darkcyan",
  },

  cart: {
    cartBorder: "1px solid #ccc",
  },
};

export const Spacing = {
  select: {
    selectNumber0: 0,
    selectNumber1: 1,
    selectNumber100: 100,
    selectFontSize11: 11,
    selectFontSize12: 12,
    selectFontSize13: 13,
    selectFontSize14: 14,
    selectFontSize16: 16,
    selectFontSize20: 20,
    selectFontSize24: 24,
    selectFontSize28: 28,
    selectFontWeight400: 400,
    selectFontWeight500: 500,
    selectFontWeight600: 600,
    selectRadius3: 3,
    selectMinusZindex: -1,

    mark: {
      selectFlex: "flex",
      selectFlexWrap: "wrap",
      selectStart: "flex-start",
      selectCenter: "center",
      selectSpaceAround: "space-around",
      selectSpaceBetween: "space-between",
      selectFlexColumn: "column",
      selectAuto: "auto",
      selectMarginAuto: "0 auto",
      selectFixed: "fixed",
      selectAbsolute: "absolute",
      selectRelative: "relative",
      selectHidden: "hidden",
      selectInhert: "inherit",
      selectTextTop: "text-top",
      selectCover: "cover",
      selectBlock: "block",
      selectInlineBlock: "inline-block",
      selectNone: "none",
      selectBold: "bold",
      selectNowrap: "nowrap",
      selectRight: "right",
      selectContentBox: "content-box",
    },
  },
  header: {
    headerWrapHeight: 7,
    headerWrapLineHeight: 7,
    headerWrapZIndex: 3000,
    headerContainerMaxWidth: 1200,
    headerItemsMenuMarginRight: 20,
    headerItemsMenuMarginTop: 1,
    headerFormContainerRight: 40,
    headerFormContainerTop: 50,
    headerFormContainerMarinTop: 1,
    headerFormControllerRadius: 5,
    headerFormControllerFontSize: 12,
    headerBadgeHeigth: 18,
    headerBadgeLineHeigth: 18,
    headerBadgeRight: 13,
    headerBadgeBottom: 15,
    headerBadgeZIndex: 100,
    headerBadgeBeforeLeft: -6,
    headerBadgeBeforeWidth: 18,
    headerBadgeBeforeHeight: 18,

    mark: {
      headerWrapPadding: "0 15",
      headerContainerPadding: "0 25",
      headerItemsNavi: "0 2",
      headerFormContainerTransform: "translateY(-50%)",
      headerFormControllerPadding: "10px 25px 10px 15px",
      headerItemsIconsPadding: "0 15",
    },
  },
  home: {
    homeWidth: 250,
    homeHeight: 320,
    homeMarinBottom: 2,
    homeCartButtonRight: 10,
    homeCartButtonTop: -60,
    homeCartButtonWidth: 45,
    homeCartButtonHeight: 45,
    homeCartButtonMarginTop: 2,

    mark: {
      homeContainerMargin: "28px 8px",
      homeDescPadding: "1rem 0",
      homePricePadding: "8px 0 15px",
      homeTransition: "all 0.3s ease",
      homeHoverScale: "scale(1.1)",
      homeHoverTranstion: "all 0.1s linear",
    },
  },
  product: {
    productWidth: 1050,
    productFlex06: 0.6,
    productFlex08: 0.8,
    productDescMarginLeft: 5,
    productBenefitPaddingBottom: 15,
    productCartWidth: 85,
    productCartMarginTop: 20,
    productCartAmountMarginBottom: 5,
    productCountOuterWidth: 85,
    productCountOuterHeight: 30,
    productCountOuterLineHeight: 30,
    productSvgMarginTop: 5,
    productTotalPaddingRight: 12,
    productTotalPaddingTop: 10,
    productLoginBenefitsPadding: 20,
    productLoginBenefitsMarginRight: 5,
    productLoginBenefitsRadius: 10,
    productIconHeight: 55,
    productIconLineHeight: 55,
    productIconButtonMarginLeft: 5,

    mark: {
      productDescPadding: "5px 0 15px",
      productPriceMargin: "15px 0 10px",
      productLoginBenefitsSpanPadding: "2px 7px",
      productIconPadding: "0 7px",
      productIconMargin: "0 5px",
      productIconSvgMargin: "0 7px",
      productIconButtonTransition: "all 0.15s linear",
    },
  },
  cart: {
    cartLabelMessageMarginTop: 10,
    cartLabelMessageSvgPadding: 10,
    cartContentWidth: 1200,
    cartTotalGroup: 50,
    cartTotalGroupCostMarginLeft: 20,
    cartListGroupWidth: 90,
    cartListGroupWidthImg: 80,

    mark: {
      cartWrapPadding: "0 100px",
      cartLabelTitlePadding: "110px 0 28px",
      cartLabelMessagePadding: "20px 0",
      cartTotalPadding: "20px 40px",
      cartListGroupPadding: "15px",
    },
  },
};
